# Build the Go Binary.
FROM golang:1.17 as build_sales-api
ENV CGO_ENABLED 0
ARG BUILD_REF

WORKDIR /service

# Copy the source code into the container.
COPY go.mod .
COPY go.sum .
COPY main.go .

# Build the service binary.

RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.14
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_sales-api /service /service
WORKDIR /service
CMD ["./my-service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="Robert Mihai" \
      org.opencontainers.image.source="https://github.com/mroobert/my-service/" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Practice"